# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lock_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'lock_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12lock_service.proto\x12\x0equorum.lock.v1\"c\n\x18\x41\x63quireLockStreamRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x0e\n\x06ttl_ms\x18\x03 \x01(\x03\x12\x17\n\x0fwait_timeout_ms\x18\x04 \x01(\x03\"B\n\rQueuedPayload\x12\x16\n\x0equeue_position\x18\x01 \x01(\x05\x12\x19\n\x11\x65stimated_wait_ms\x18\x02 \x01(\x03\"W\n\x0eGrantedPayload\x12\x13\n\x0b\x66\x65nce_token\x18\x01 \x01(\x03\x12\x19\n\x11lease_duration_ms\x18\x02 \x01(\x03\x12\x15\n\rexpires_at_ms\x18\x03 \x01(\x03\"!\n\x0fRejectedPayload\x12\x0e\n\x06reason\x18\x01 \x01(\t\"\x88\x02\n\x0fLockStreamEvent\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x31\n\nevent_type\x18\x03 \x01(\x0e\x32\x1d.quorum.lock.v1.LockEventType\x12/\n\x06queued\x18\x04 \x01(\x0b\x32\x1d.quorum.lock.v1.QueuedPayloadH\x00\x12\x31\n\x07granted\x18\x05 \x01(\x0b\x32\x1e.quorum.lock.v1.GrantedPayloadH\x00\x12\x33\n\x08rejected\x18\x06 \x01(\x0b\x32\x1f.quorum.lock.v1.RejectedPayloadH\x00\x42\t\n\x07payload\"I\n\x12ReleaseLockRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x13\n\x0b\x66\x65nce_token\x18\x03 \x01(\x03\"7\n\x13ReleaseLockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*\xc9\x01\n\rLockEventType\x12\x1f\n\x1bLOCK_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n\x16LOCK_EVENT_TYPE_QUEUED\x10\x01\x12\x1b\n\x17LOCK_EVENT_TYPE_GRANTED\x10\x02\x12\x1c\n\x18LOCK_EVENT_TYPE_REJECTED\x10\x03\x12\x1b\n\x17LOCK_EVENT_TYPE_EXPIRED\x10\x04\x12#\n\x1fLOCK_EVENT_TYPE_LEADERSHIP_LOST\x10\x05\x32\xc7\x01\n\x0bLockService\x12`\n\x11\x41\x63quireLockStream\x12(.quorum.lock.v1.AcquireLockStreamRequest\x1a\x1f.quorum.lock.v1.LockStreamEvent0\x01\x12V\n\x0bReleaseLock\x12\".quorum.lock.v1.ReleaseLockRequest\x1a#.quorum.lock.v1.ReleaseLockResponseB\x03\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lock_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\001'
  _globals['_LOCKEVENTTYPE']._serialized_start=731
  _globals['_LOCKEVENTTYPE']._serialized_end=932
  _globals['_ACQUIRELOCKSTREAMREQUEST']._serialized_start=38
  _globals['_ACQUIRELOCKSTREAMREQUEST']._serialized_end=137
  _globals['_QUEUEDPAYLOAD']._serialized_start=139
  _globals['_QUEUEDPAYLOAD']._serialized_end=205
  _globals['_GRANTEDPAYLOAD']._serialized_start=207
  _globals['_GRANTEDPAYLOAD']._serialized_end=294
  _globals['_REJECTEDPAYLOAD']._serialized_start=296
  _globals['_REJECTEDPAYLOAD']._serialized_end=329
  _globals['_LOCKSTREAMEVENT']._serialized_start=332
  _globals['_LOCKSTREAMEVENT']._serialized_end=596
  _globals['_RELEASELOCKREQUEST']._serialized_start=598
  _globals['_RELEASELOCKREQUEST']._serialized_end=671
  _globals['_RELEASELOCKRESPONSE']._serialized_start=673
  _globals['_RELEASELOCKRESPONSE']._serialized_end=728
  _globals['_LOCKSERVICE']._serialized_start=935
  _globals['_LOCKSERVICE']._serialized_end=1134
_builder.BuildServices(DESCRIPTOR, 'lock_service_pb2', _globals)
# @@protoc_insertion_point(module_scope)
