# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from quorum.proto import lock_service_pb2 as lock__service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lock_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LockServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireLockStream = channel.unary_stream(
                '/quorum.lock.v1.LockService/AcquireLockStream',
                request_serializer=lock__service__pb2.AcquireLockStreamRequest.SerializeToString,
                response_deserializer=lock__service__pb2.LockStreamEvent.FromString,
                _registered_method=True)
        self.ReleaseLock = channel.unary_unary(
                '/quorum.lock.v1.LockService/ReleaseLock',
                request_serializer=lock__service__pb2.ReleaseLockRequest.SerializeToString,
                response_deserializer=lock__service__pb2.ReleaseLockResponse.FromString,
                _registered_method=True)


class LockServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AcquireLockStream(self, request, context):
        """Server-streaming RPC for push-based lock acquisition and queuing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireLockStream': grpc.unary_stream_rpc_method_handler(
                    servicer.AcquireLockStream,
                    request_deserializer=lock__service__pb2.AcquireLockStreamRequest.FromString,
                    response_serializer=lock__service__pb2.LockStreamEvent.SerializeToString,
            ),
            'ReleaseLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLock,
                    request_deserializer=lock__service__pb2.ReleaseLockRequest.FromString,
                    response_serializer=lock__service__pb2.ReleaseLockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quorum.lock.v1.LockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quorum.lock.v1.LockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LockService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AcquireLockStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/quorum.lock.v1.LockService/AcquireLockStream',
            lock__service__pb2.AcquireLockStreamRequest.SerializeToString,
            lock__service__pb2.LockStreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.lock.v1.LockService/ReleaseLock',
            lock__service__pb2.ReleaseLockRequest.SerializeToString,
            lock__service__pb2.ReleaseLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
