# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x0bquorum.raft\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x03\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"k\n\rLogEntryProto\x12\r\n\x05index\x18\x01 \x01(\x03\x12\x0c\n\x04term\x18\x02 \x01(\x03\x12\x14\n\x0c\x63ommand_type\x18\x03 \x01(\t\x12\x11\n\tdata_json\x18\x04 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\"\xaa\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x03\x12\x15\n\rprev_log_term\x18\x04 \x01(\x03\x12+\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x1a.quorum.raft.LogEntryProto\x12\x15\n\rleader_commit\x18\x06 \x01(\x03\"c\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x13\n\x0bmatch_index\x18\x03 \x01(\x03\x12\x16\n\x0e\x63onflict_index\x18\x04 \x01(\x03\"\x8e\x01\n\x16InstallSnapshotRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x1b\n\x13last_included_index\x18\x03 \x01(\x03\x12\x1a\n\x12last_included_term\x18\x04 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x0c\n\x04\x64one\x18\x06 \x01(\x08\"\'\n\x17InstallSnapshotResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x32\x95\x02\n\x0bRaftService\x12P\n\x0bRequestVote\x12\x1f.quorum.raft.RequestVoteRequest\x1a .quorum.raft.RequestVoteResponse\x12V\n\rAppendEntries\x12!.quorum.raft.AppendEntriesRequest\x1a\".quorum.raft.AppendEntriesResponse\x12\\\n\x0fInstallSnapshot\x12#.quorum.raft.InstallSnapshotRequest\x1a$.quorum.raft.InstallSnapshotResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTVOTEREQUEST']._serialized_start=27
  _globals['_REQUESTVOTEREQUEST']._serialized_end=130
  _globals['_REQUESTVOTERESPONSE']._serialized_start=132
  _globals['_REQUESTVOTERESPONSE']._serialized_end=189
  _globals['_LOGENTRYPROTO']._serialized_start=191
  _globals['_LOGENTRYPROTO']._serialized_end=298
  _globals['_APPENDENTRIESREQUEST']._serialized_start=301
  _globals['_APPENDENTRIESREQUEST']._serialized_end=471
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=473
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=572
  _globals['_INSTALLSNAPSHOTREQUEST']._serialized_start=575
  _globals['_INSTALLSNAPSHOTREQUEST']._serialized_end=717
  _globals['_INSTALLSNAPSHOTRESPONSE']._serialized_start=719
  _globals['_INSTALLSNAPSHOTRESPONSE']._serialized_end=758
  _globals['_RAFTSERVICE']._serialized_start=761
  _globals['_RAFTSERVICE']._serialized_end=1038
# @@protoc_insertion_point(module_scope)
