# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from quorum.proto import quorum_pb2 as quorum__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in quorum_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuorumServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireLock = channel.unary_unary(
                '/quorum.api.QuorumService/AcquireLock',
                request_serializer=quorum__pb2.AcquireLockRequest.SerializeToString,
                response_deserializer=quorum__pb2.AcquireLockResponse.FromString,
                _registered_method=True)
        self.RenewLock = channel.unary_unary(
                '/quorum.api.QuorumService/RenewLock',
                request_serializer=quorum__pb2.RenewLockRequest.SerializeToString,
                response_deserializer=quorum__pb2.RenewLockResponse.FromString,
                _registered_method=True)
        self.ReleaseLock = channel.unary_unary(
                '/quorum.api.QuorumService/ReleaseLock',
                request_serializer=quorum__pb2.ReleaseLockRequest.SerializeToString,
                response_deserializer=quorum__pb2.ReleaseLockResponse.FromString,
                _registered_method=True)
        self.GetLock = channel.unary_unary(
                '/quorum.api.QuorumService/GetLock',
                request_serializer=quorum__pb2.GetLockRequest.SerializeToString,
                response_deserializer=quorum__pb2.GetLockResponse.FromString,
                _registered_method=True)
        self.WatchLeader = channel.unary_stream(
                '/quorum.api.QuorumService/WatchLeader',
                request_serializer=quorum__pb2.WatchLeaderRequest.SerializeToString,
                response_deserializer=quorum__pb2.LeaderNotification.FromString,
                _registered_method=True)


class QuorumServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AcquireLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuorumServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireLock': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLock,
                    request_deserializer=quorum__pb2.AcquireLockRequest.FromString,
                    response_serializer=quorum__pb2.AcquireLockResponse.SerializeToString,
            ),
            'RenewLock': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewLock,
                    request_deserializer=quorum__pb2.RenewLockRequest.FromString,
                    response_serializer=quorum__pb2.RenewLockResponse.SerializeToString,
            ),
            'ReleaseLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLock,
                    request_deserializer=quorum__pb2.ReleaseLockRequest.FromString,
                    response_serializer=quorum__pb2.ReleaseLockResponse.SerializeToString,
            ),
            'GetLock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLock,
                    request_deserializer=quorum__pb2.GetLockRequest.FromString,
                    response_serializer=quorum__pb2.GetLockResponse.SerializeToString,
            ),
            'WatchLeader': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchLeader,
                    request_deserializer=quorum__pb2.WatchLeaderRequest.FromString,
                    response_serializer=quorum__pb2.LeaderNotification.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quorum.api.QuorumService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quorum.api.QuorumService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuorumService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AcquireLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.api.QuorumService/AcquireLock',
            quorum__pb2.AcquireLockRequest.SerializeToString,
            quorum__pb2.AcquireLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.api.QuorumService/RenewLock',
            quorum__pb2.RenewLockRequest.SerializeToString,
            quorum__pb2.RenewLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.api.QuorumService/ReleaseLock',
            quorum__pb2.ReleaseLockRequest.SerializeToString,
            quorum__pb2.ReleaseLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.api.QuorumService/GetLock',
            quorum__pb2.GetLockRequest.SerializeToString,
            quorum__pb2.GetLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/quorum.api.QuorumService/WatchLeader',
            quorum__pb2.WatchLeaderRequest.SerializeToString,
            quorum__pb2.LeaderNotification.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
